### ISSUE TITLE
tcp.payload

### ISSUE THREAD

**Issue by P3nd1ng** [Byxs20/FlowAnalyzer#2]
出现KeyError: 'tcp.payload'是什么原因

**Comment by Byxs20** [comment]
**啥也没有你这个issue不如不发**

**Comment by P3nd1ng** [comment]
display_filter = "http.request or http.response"就改了这一点，处理其他流量报错QAQ

Traceback (most recent call last):
  File "d:/test/demo.py", line 11, in <module>
    for count, http in enumerate(FlowAnalyzer(jsonPath).generate_http_dict_pairs(), start=1):
  File "C:\Users\\AppData\Local\Programs\Python\Python38\lib\site-packages\FlowAnalyzer\FlowAnalyzer.py", line 117, in generate_http_dict_pairs
    requests, responses = self.parse_http_json()
  File "C:\Users\\AppData\Local\Programs\Python\Python38\lib\site-packages\FlowAnalyzer\FlowAnalyzer.py", line 85, in parse_http_json
    packet["tcp.reassembled.data"][0] if packet.get("tcp.reassembled.data") else packet["tcp.payload"][0]
KeyError: 'tcp.payload'

**Comment by Byxs20** [comment]
你这个也不详细，所以你配置了tshark到系统环境变量了么，还有你测试了示例的demo了没？

**Comment by P3nd1ng** [comment]
解决了b神，我用http.request or http.response筛选流量时出现了一些奇怪的流量，我比较菜也不知道是啥
![a3aa42db09d30554e7c44d7e517bb8c](https://github.com/user-attachments/assets/e468a6bf-311d-4a4d-83e3-094127ba03c8) 处理这些流量的时候就报KeyError:'tcp.payload'的错误
