### ISSUE TITLE
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)

### ISSUE THREAD

**Issue by zihaveaDream** [Byxs20/FlowAnalyzer#3]
版本：FlowAnalyzer 0.3.3
Python：3.10.0
OS：Windows11

1、已配置 tshark.exe 环境变量，测试运行无误

```
E:\Cache\Scripts-All\flowAnalyzer\FlowAnalyzer-main\tests>tshark.exe -n -r "flow.pcapng" -Y "http" -T fields -e http.request.uri -E header=y -E separator=/t 

/upload/php_eval_xor_base64.php
/upload/php_eval_xor_base64.php
/upload/php_eval_xor_base64.php
http.request.uri
```

2、无法顺利运行 demo.py 文件
```
Traceback (most recent call last):
  File "E:\Cache\Scripts-All\flowAnalyzer\FlowAnalyzer-main\tests\demo.py", line 11, in <module>
    jsonPath = FlowAnalyzer.get_json_data(flowPath, display_filter=display_filter)
  File "D:\App\Environment\Python\Python310\lib\site-packages\FlowAnalyzer\FlowAnalyzer.py", line 229, in get_json_data
    data = json.load(f)
  File "D:\App\Environment\Python\Python310\lib\json\__init__.py", line 293, in load
    return loads(fp.read(),
  File "D:\App\Environment\Python\Python310\lib\json\__init__.py", line 346, in loads
    return _default_decoder.decode(s)
  File "D:\App\Environment\Python\Python310\lib\json\decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "D:\App\Environment\Python\Python310\lib\json\decoder.py", line 355, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)
[Finished in 182ms]
```

3、我看了下 output.json 这个文件一直是空的，不知道为什么。。。

路径也是纯英文，也不存在权限问题

**Comment by Byxs20** [comment]
1. cmd运行 `tshark -v` 确定tshark能正确显示版本
2. 删除 `output.json` 调用 `demo.py` 试试

我的版本：
```
tshark version: 4.0.11
```

**Comment by zihaveaDream** [comment]
```
E:\Cache\Scripts-All\flowAnalyzer\FlowAnalyzer-main>tshark -v
TShark (Wireshark) 4.0.0 (v4.0.0-0-g0cbe09cd796b).
```

感谢b神，我在删除 `output.json` 后调用 `demo.py` 就可以了。

# 另外我还遇到了这个问题，麻烦帮忙看看是什么原因：

```
E:\Cache\Scripts-All\flowAnalyzer\output.json
Traceback (most recent call last):
  File "E:\Cache\Scripts-All\flowAnalyzer\http_flow_extract.py", line 22, in <module>
    for count, http in enumerate(FlowAnalyzer(jsonPath).generate_http_dict_pairs(), start=1):
  File "D:\App\Environment\Python\Python310\lib\site-packages\FlowAnalyzer\FlowAnalyzer.py", line 140, in generate_http_dict_pairs
    requests, responses = self.parse_http_json()
  File "D:\App\Environment\Python\Python310\lib\site-packages\FlowAnalyzer\FlowAnalyzer.py", line 115, in parse_http_json
    frame_num, request_in, time_epoch, full_uri, full_request = self.parse_packet(packet)
  File "D:\App\Environment\Python\Python310\lib\site-packages\FlowAnalyzer\FlowAnalyzer.py", line 97, in parse_packet
    full_request = packet["exported_pdu.exported_pdu"][0]
KeyError: 'exported_pdu.exported_pdu'
```

我这是一段 `RSA` 加密的 `TLS` pcap 数据包，我通过 `wireshark` 导入私钥，通过 `wireshark`可以正常分析。
通过 `tshark` 也可以获取解密后的数据，如下：

```
D:\>tshark.exe -n -r "9.pcap" -Y "tcp.stream == 2668" -T fields -e http.request.uri -E header=y -E separator=/t

http.request.uri
/logon/LogonPoint/custom/style.css
/logon/LogonPoint/receiver/images/2x/actionSprite@2x.png
/logon/LogonPoint/receiver/js/external/elliptic.min.js
/vpn/theme/a.txt

```

补充：我把更新到 wireshark 最新版本也是同样的报错。

```
E:\Cache\Scripts-All\flowAnalyzer>tshark -v
TShark (Wireshark) 4.2.6 (v4.2.6-0-g2acd1a854bab).
```

**Comment by Byxs20** [comment]
```
if packet.get("tcp.reassembled.data"):
    full_request = packet["tcp.reassembled.data"][0]
elif packet.get("tcp.payload"):
    full_request = packet["tcp.payload"][0]
else:
    # exported_pdu.exported_pdu
    full_request = packet["exported_pdu.exported_pdu"][0]
return frame_num, request_in, time_epoch, full_uri, full_request
```
根据代码可以看到是去解析json的内容，流程：如果有 `tcp.reassembled.data` 就用 `tcp.reassembled.data`，没有就判断有没有 `tcp.payload`，如果还没有的话就去用 `exported_pdu.exported_pdu`

正常情况前两个地方肯定就会满足了结束了，如果前两个都没有的话，那么他就不是一个tcp的

顺嘴说一句，你用 `wireshark` 去导入RSA密钥到流量包的话，使用我的库是无法帮忙解密RSA的。

**Comment by zihaveaDream** [comment]
我看了下 output.json 文件，里面有 2132 个 `tcp.reassembled.data`，10615 个 `tcp.payload`，这种情况下怎么判断呢？


其中一个片段示例：
```
{
    "_index": "packets-2024-07-29",
    "_type": "doc",
    "_score": null,
    "_source": {
      "layers": {
        "tcp.reassembled.data": [
          "16030106e0010006dc0303170c23bc54f8fea00acde1eb3767ca0fd8f90f47e3fe5db523f89efcfcc8495b209823989df31de77ce31d45536714d1adb8c72268f9af1d5b3045524b77307c1600207a7a130113021303c02bc02fc02cc030cca9cca8c013c014009c009d002f003501000673fafa0000003304ef04ed9a9a000100639904c04b75f9d7c537326c35170a801ac91dbda5bf9ebd65289c7fd94e313c010b2a6deb17693dd174244ac3d5348fef507157149f9d13774e17bddca3370b17240db416c536a33023cc961523cff1b462cac92a146b95c8660f084f7aa00387fc6d0de1621559278e1aa7f67387b707d0c8b625241891e020838db9098e049d604624fde898a849b100c68854ca6c98a5a1825a5b487528bcec8a20d3cfb72255f5397b8359c49171afa70a9926d9acd99304c252b34885ad893c047c9977f5362ba16cae6012032aba49ef4c761f73ca209b9e33399e7db66c7b489633382117b3785c93162910cd28959c7bf1ad5fc87511ac52c99c50cef60f8c55a92880c96540a9e34908eb229ed26bc32bf05484bb51900aab7da817cae87534a037a62b35198b31f4278fb99708d677404fea127db87c80455b0ecfc47ec469c5f4a777b2990952ca90d970c3df747b7c3421e412fb5a5bfeba0a8d61b7d0980309000728fe99093f439bc1b1b2a5c7eb0dbadb31a871b3685e57b2efce566f4092db9d9caf0817c81e90c01dc31e6a7be71f53c74758cc80920fc59bef09b8335b73946a88f12b4bec15b9c4376a6da49a39b621729c9b6e855b4610792d0ba39947bab63733714640a8004490bb131ab172e70c87fa641ae5482b2f3443a174817c700351ef24ffac1b044ca5d95245d3eb271f5191518e97fe59139d022203d8b96d8823073a3afc26740eba256af2908a69155815cab86d71ba24a843fe0bc6adc9497518df0e54e1fc9a4fb4543581c8edd98c7b588158974a80fd0b8b811181bca2746e257cda54e4fe7560da7572b9b0f5e8a40869568b6c950d61a8d5c93585df1c228a1460463375fa26087a967fbd9b8c4723149f138a38a292612c3cab763374a3e207c3c8d8a12096154d3db874e049c9ea018a6a762ebf355d3a62319e43a0231c08b07b9af03b507945efe0857815037eb56814429c9ea744e56315f271098522a11c6eab2ffda818329ab65f291f30ac84963a98c744ac40083afd594238a62de324d26fab6cfc3093844478a62501c67ca8cf3535d1abc57fbcd999c5e5f94c871ac0ddcc06fcbc08d94f9caa897c398fb5cf19535d365c4ab496866ec47d25878285a6aeff642b6aac074961d0f538e42311b17d88931a72a8ae9bdd0444597aa4eddc9c6d523afddeb9ab84bc26ec8b344c76312cb621e12ab2c7a71630998b33c62487cacc0b73744d5b894223604ab7811b1aa696871a1ca43f4ea11969050e008ba7d37954a512c405b20af3bad6cf63e54b940bdcc673ff27976726caaa00ba74cbdb9d6186f1acd7dbccf70010eb2a1bb1aa026b1294f1857487e892afe0b7f5ba14dc9e295bfb98667031f2a0b95576b728809b6230906c30c6eae247081c9a1adea00f07a8bf442b265600766f6ac7f391a9ec41a00bd363fe9b41c422753265fb6bba8193565c745c31b084a462a3aefd82be3a04568cb48dde5b3080c53c4f88956e2a6a3043576ca614eb80bf1d7a5b0a7253ea60319039dc6055fb50c1815027d27e2a4ea1869033c59cd7621c660166ed642c4f562aa80ca474079ada790eb65072d43baf41c2d5169be73b831d3431648ebb85defec33927715d3587023850ece001d0020193bd0e8f8d6c55bb193fe4b10c41d80dc1981bb868e97c4088f9a0ed546827300170000000d0012001004030804040105030805050108060601ff01000100000500050100000000001b0003020002002b0007067a7a0304030300120000000a000c000a9a9a6399001d00170018fe0d00fa0000010001ef00203e0a897a3a94dd8557108280fabcb280341b47409fe18aba892092bff013463500d015d2184091ec86e1918d275b0a07759b0515e4acc2c20140693a0b39872e3a9edb01e4a4ee2150527751164d7a656331c1157feb2e6507ef90432fbea0221d01f577197ff981c41bd1c17c1e56e99ee0af44ae7a780ee8d1e4836de4e1efad25df51cc0c21bd924388aa9a763b0fa7e54183a888bf39fbb67cfe6ac4e5a07e111013c2e985676959aad098f924d07b24caa2cf85ccce28877b94b95c8534cfc70c0540db2ea714a8770f3b8646f122bb1e16e97df9e17c65c8fec6086efba011e34f708717a77643866c141e8850c863000b00020100446900050003026832002300000010000e000c02683208687474702f312e31002d000201014a4a000100"
        ],
        "frame.number": [
          "41522"
        ],
        "tcp.payload": [
          "7023850ece001d0020193bd0e8f8d6c55bb193fe4b10c41d80dc1981bb868e97c4088f9a0ed546827300170000000d0012001004030804040105030805050108060601ff01000100000500050100000000001b0003020002002b0007067a7a0304030300120000000a000c000a9a9a6399001d00170018fe0d00fa0000010001ef00203e0a897a3a94dd8557108280fabcb280341b47409fe18aba892092bff013463500d015d2184091ec86e1918d275b0a07759b0515e4acc2c20140693a0b39872e3a9edb01e4a4ee2150527751164d7a656331c1157feb2e6507ef90432fbea0221d01f577197ff981c41bd1c17c1e56e99ee0af44ae7a780ee8d1e4836de4e1efad25df51cc0c21bd924388aa9a76ea714a8770f3b8646f122bb1e16e97df9e17c65c8fec6086efba011e34f708717a77643866c141e8850c863000b00020100446900050003026832002300000010000e000c02683208687474702f312e31002d000201014a4a000100"
        ],
        "frame.time_epoch": [
          "1722217739.051330000"
        ]
      }
    }
  }
```


PS：针对我这种 RSA 加密流量情况，B神有什么建议吗？

**Comment by Byxs20** [comment]
第一个字段优先（重组tcp肯定是优先的）   想办法找个命令能够让tshark给rsa流量解密后导出一份新的流量  Google搜搜 我不太清楚
